print('Hello')
print('World')
print()
print('Hello', end='')
print('World')
print()
print('Jimmy', end='')
print('Jenan')
print()
print('cats', 'dogs', 'mice')
print('cats', 'dogs', 'mice', sep=',')
print('cats', ' dogs', ' mice', sep=',')
print('cats', 'dogs', 'mice', sep='/')
print('cats', ' dogs', ' mice', sep='')


